import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import DeliveryFullBaner from "./_components/DelivryFullBanner";
import { CartProvider } from "./_contexts/ProductCartContext";
import ThemeButton from "./_components/XstateThemeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};
// Only the root layout can contain <html> and <body> tags.
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <DeliveryFullBaner />
          <div className="pt-[40px]" />

          <Navbar />

          {/* this div create space between the fixed navbar and the content. so it doesnt cut like title for ex... */}
          <div className="pt-[105px]" />
          <ThemeButton/>
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
